### ISSUE TITLE
Make log plugin usable for different clouds

### ISSUE THREAD

**Issue by Ruadhri17** [thin-edge/thin-edge.io#2048]
**Is your refactoring request related to a problem? Please describe.**
This ticket is part of #2017. It considers moving cloud-specific logic to the mapper or refactoring it to be cloud agnostic. 

**Describe the solution you'd like**

1. Move cloud specific logic from the c8y-log-plugin to the mapper
2. Rename the c8y-log-plugin to tedge-log-plugin once all cloud specific logic has been moved.

**Describe alternatives you've considered**

**Additional context**
See #2017

**Tasks**
- [x] tedge-log-plugin specification: #2069 
- [x] tedge-log-plugin code change: #2086 
- [x] c8y-mapper code change:  #2108 
- [x] Robot framework test: https://github.com/thin-edge/thin-edge.io/pull/2213
- [x] Update specs to align with implemenentation after tedge-log-plugin and c8y-mapper PR are merged. #2216 
- [x] Introduce `root.topic` and `device.topic` to tedge config so that tedge-log-plugin and c8y-mapper can use them. (later?)

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.

**Comment by rina23q** [comment]
@reubenmiller Why is this ticket still opened?

**Comment by reubenmiller** [comment]
> @reubenmiller Why is this ticket still opened?

I just forgot to close it after marking it with the 0.13.0 milestone (apparently)
