### ISSUE TITLE
Make configuration plugin usable for different clouds

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2098]
**Is your refactoring request related to a problem? Please describe.**
This ticket is part of #2017. It considers moving cloud-specific logic to the mapper or refactoring it to be cloud agnostic. 

**Describe the solution you'd like**

1. Move cloud specific logic from the c8y-configuration-plugin to the mapper
2. Rename the c8y-configuration-plugin to tedge-configuration-plugin once all cloud specific logic has been moved.

**Describe alternatives you've considered**

**Additional context**
See #2017

**Tasks**
- [x] tedge-configuration-plugin specification: #2097  
- [x] tedge-configuration-plugin code change: #2238 
- [x] tedge-mapper c8y code change: #2292
- [x] Robotframework test: #2368
- [x] Delist c8y-configuration-plugin reference guide and make tedge-configuration-plugin user guide available in our doc in "Next":

**Comment by rina23q** [comment]
Tasks:

- [ ] tedge-configuration-plugin specification: #2097  
- [ ] tedge-configuration-plugin code change:
- [ ] c8y-mapper code change:

**Comment by reubenmiller** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
