### ISSUE TITLE
Resolving webpki security advisory

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2183]
## TODO

- [ ] verify no regression in `c8y_remote_access_plugin`
- [ ] rework error downcasting in `crates/common/certificate/src/lib.rs:153`
- [ ] update dependencies in `mqtt_channel` and `certificate` so that `rustls` is the same version between them
- [ ] update `rustls` in remaining crates

## Initial problem

`cargo audit` reported 2 vulns: `webpki` and `rustls-webpki`: https://github.com/thin-edge/thin-edge.io/actions/runs/5939407296/job/16105728278

`rustls-webpki` was easily fixed by upgrading the package patch version: #2180 

There are more problems with `webpki`, which is unmaintained and won't be patched, so ideally we should upgrade all our dependencies to versions where `webpki` is not used by them anymore.

According to the [security advisory](https://rustsec.org/advisories/RUSTSEC-2023-0052):

> When this crate is given a pathological certificate chain to validate, it will spend CPU time exponential with the number of candidate certificates at each step of path building.
>
> Both TLS clients and TLS servers that accept client certificate are affected.
>
> This was previously reported in [https://github.com/briansmith/webpki/issues/69](https://github.com/briansmith/webpki/issues/69) and re-reported recently by Luke Malinowski.
>
> `rustls-webpki` is a fork of this crate which contains a fix for this issue and is actively maintained.

In the case of thin-edge, I don't think that this attack vector is available, as we only connect to hosts specified by the user in the config, so to make use of this vuln, an attacker would need to already have a physical access to the device.

So theoretically we could ignore this vuln, but the bigger problem is with using an unmaintained crate, perhaps more vulns could be discovered forcing us to upgrade later, with potentially more conflicts, that's why it would be better to upgrade sooner than later. 

## Performing an upgrade

Here is a `cargo-adit` report with a dependency tree:

```
Crate:     webpki
Version:   0.22.0
Title:     webpki: CPU denial of service in certificate path building
Date:      2023-08-22
ID:        RUSTSEC-2023-0052
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0052
Severity:  7.5 (high)
Solution:  No fixed upgrade is available!
Dependency tree:
webpki 0.22.0
├── tungstenite 0.17.3
│   ├── ws_stream_tungstenite 0.9.0
│   │   └── c8y-remote-access-plugin 0.12.0
│   ├── c8y-remote-access-plugin 0.12.0
│   └── async-tungstenite 0.18.0
│       ├── ws_stream_tungstenite 0.9.0
│       └── c8y-remote-access-plugin 0.12.0
├── tokio-rustls 0.23.4
│   ├── rumqttd 0.11.0
│   │   └── mqtt_tests 0.12.0
│   │       ├── tedge_mqtt_ext 0.12.0
│   │       │   ├── tedge_log_manager 0.12.0
│   │       │   │   └── tedge-log-plugin 0.12.0
│   │       │   ├── tedge_health_ext 0.12.0
│   │       │   │   ├── tedge-mapper 0.12.0
│   │       │   │   ├── tedge-log-plugin 0.12.0
│   │       │   │   ├── tedge-agent 0.12.0
│   │       │   │   ├── c8y-log-plugin 0.12.0
│   │       │   │   ├── c8y-firmware-plugin 0.12.0
│   │       │   │   ├── c8y-device-management 0.12.0
│   │       │   │   └── c8y-configuration-plugin 0.12.0
│   │       │   ├── tedge-mapper 0.12.0
│   │       │   ├── tedge-log-plugin 0.12.0
│   │       │   ├── tedge-agent 0.12.0
│   │       │   ├── collectd_ext 0.12.0
│   │       │   │   └── tedge-mapper 0.12.0
│   │       │   ├── c8y_mapper_ext 0.12.0
│   │       │   │   └── tedge-mapper 0.12.0
│   │       │   ├── c8y_log_manager 0.12.0
│   │       │   │   ├── c8y-log-plugin 0.12.0
│   │       │   │   └── c8y-device-management 0.12.0
│   │       │   ├── c8y_firmware_manager 0.12.0
│   │       │   │   ├── c8y-firmware-plugin 0.12.0
│   │       │   │   └── c8y-device-management 0.12.0
│   │       │   ├── c8y_config_manager 0.12.0
│   │       │   │   ├── c8y-device-management 0.12.0
│   │       │   │   └── c8y-configuration-plugin 0.12.0
│   │       │   ├── c8y-log-plugin 0.12.0
│   │       │   ├── c8y-firmware-plugin 0.12.0
│   │       │   ├── c8y-device-management 0.12.0
│   │       │   ├── c8y-configuration-plugin 0.12.0
│   │       │   ├── az_mapper_ext 0.12.0
│   │       │   │   └── tedge-mapper 0.12.0
│   │       │   └── aws_mapper_ext 0.12.0
│   │       │       └── tedge-mapper 0.12.0
│   │       ├── tedge 0.12.0
│   │       └── mqtt_channel 0.12.0
│   │           ├── tedge_utils 0.12.0
│   │           │   ├── tedge_log_manager 0.12.0
│   │           │   ├── tedge_file_system_ext 0.12.0
│   │           │   │   ├── tedge_log_manager 0.12.0
│   │           │   │   ├── tedge-mapper 0.12.0
│   │           │   │   ├── tedge-log-plugin 0.12.0
│   │           │   │   ├── c8y_mapper_ext 0.12.0
│   │           │   │   ├── c8y_log_manager 0.12.0
│   │           │   │   ├── c8y_config_manager 0.12.0
│   │           │   │   ├── c8y-log-plugin 0.12.0
│   │           │   │   ├── c8y-device-management 0.12.0
│   │           │   │   └── c8y-configuration-plugin 0.12.0
│   │           │   ├── tedge_downloader_ext 0.12.0
│   │           │   │   ├── c8y_firmware_manager 0.12.0
│   │           │   │   ├── c8y-firmware-plugin 0.12.0
│   │           │   │   └── c8y-device-management 0.12.0
│   │           │   ├── tedge_config 0.12.0
│   │           │   │   ├── tedge_log_manager 0.12.0
│   │           │   │   ├── tedge-watchdog 0.12.0
│   │           │   │   ├── tedge-mapper 0.12.0
│   │           │   │   ├── tedge-log-plugin 0.12.0
│   │           │   │   ├── tedge-apt-plugin 0.12.0
│   │           │   │   ├── tedge-agent 0.12.0
│   │           │   │   ├── tedge 0.12.0
│   │           │   │   ├── sawtooth-publisher 0.12.0
│   │           │   │   ├── plugin_sm 0.12.0
│   │           │   │   │   ├── tedge-agent 0.12.0
│   │           │   │   │   └── c8y_mapper_ext 0.12.0
│   │           │   │   ├── c8y_mapper_ext 0.12.0
│   │           │   │   ├── c8y_log_manager 0.12.0
│   │           │   │   ├── c8y_http_proxy 0.12.0
│   │           │   │   │   ├── tedge-mapper 0.12.0
│   │           │   │   │   ├── c8y_mapper_ext 0.12.0
│   │           │   │   │   ├── c8y_log_manager 0.12.0
│   │           │   │   │   ├── c8y_firmware_manager 0.12.0
│   │           │   │   │   ├── c8y_config_manager 0.12.0
│   │           │   │   │   ├── c8y-log-plugin 0.12.0
│   │           │   │   │   ├── c8y-firmware-plugin 0.12.0
│   │           │   │   │   ├── c8y-device-management 0.12.0
│   │           │   │   │   └── c8y-configuration-plugin 0.12.0
│   │           │   │   ├── c8y_firmware_manager 0.12.0
│   │           │   │   ├── c8y_config_manager 0.12.0
│   │           │   │   ├── c8y_api 0.12.0
│   │           │   │   │   ├── c8y_mapper_ext 0.12.0
│   │           │   │   │   ├── c8y_log_manager 0.12.0
│   │           │   │   │   ├── c8y_http_proxy 0.12.0
│   │           │   │   │   ├── c8y_firmware_manager 0.12.0
│   │           │   │   │   ├── c8y_config_manager 0.12.0
│   │           │   │   │   └── c8y-remote-access-plugin 0.12.0
│   │           │   │   ├── c8y-remote-access-plugin 0.12.0
│   │           │   │   ├── c8y-log-plugin 0.12.0
│   │           │   │   ├── c8y-firmware-plugin 0.12.0
│   │           │   │   ├── c8y-device-management 0.12.0
│   │           │   │   └── c8y-configuration-plugin 0.12.0
│   │           │   ├── tedge-watchdog 0.12.0
│   │           │   ├── tedge-mapper 0.12.0
│   │           │   ├── tedge-apt-plugin 0.12.0
│   │           │   ├── tedge-agent 0.12.0
│   │           │   ├── tedge 0.12.0
│   │           │   ├── download 0.12.0
│   │           │   │   ├── tedge_downloader_ext 0.12.0
│   │           │   │   ├── tedge_api 0.12.0
│   │           │   │   │   ├── tedge_health_ext 0.12.0
│   │           │   │   │   ├── tedge-watchdog 0.12.0
│   │           │   │   │   ├── tedge-agent 0.12.0
│   │           │   │   │   ├── plugin_sm 0.12.0
│   │           │   │   │   ├── collectd_ext 0.12.0
│   │           │   │   │   ├── c8y_mapper_ext 0.12.0
│   │           │   │   │   ├── c8y_log_manager 0.12.0
│   │           │   │   │   ├── c8y_firmware_manager 0.12.0
│   │           │   │   │   ├── c8y_config_manager 0.12.0
│   │           │   │   │   ├── c8y_api 0.12.0
│   │           │   │   │   ├── az_mapper_ext 0.12.0
│   │           │   │   │   └── aws_mapper_ext 0.12.0
│   │           │   │   ├── plugin_sm 0.12.0
│   │           │   │   ├── c8y_http_proxy 0.12.0
│   │           │   │   └── c8y_api 0.12.0
│   │           │   ├── c8y_mapper_ext 0.12.0
│   │           │   ├── c8y_log_manager 0.12.0
│   │           │   ├── c8y_http_proxy 0.12.0
│   │           │   ├── c8y_firmware_manager 0.12.0
│   │           │   ├── c8y_config_manager 0.12.0
│   │           │   ├── c8y_api 0.12.0
│   │           │   ├── c8y-remote-access-plugin 0.12.0
│   │           │   ├── c8y-log-plugin 0.12.0
│   │           │   └── c8y-configuration-plugin 0.12.0
│   │           ├── tedge_mqtt_ext 0.12.0
│   │           ├── tedge_config 0.12.0
│   │           ├── tedge_api 0.12.0
│   │           ├── tedge-watchdog 0.12.0
│   │           ├── tedge-mapper 0.12.0
│   │           ├── sawtooth-publisher 0.12.0
│   │           ├── c8y_http_proxy 0.12.0
│   │           └── c8y_api 0.12.0
│   ├── rumqttc 0.18.0
│   │   ├── tedge 0.12.0
│   │   ├── mqtt_tests 0.12.0
│   │   └── mqtt_channel 0.12.0
│   ├── hyper-rustls 0.23.2
│   │   └── tedge_http_ext 0.12.0
│   │       ├── tedge_log_manager 0.12.0
│   │       ├── tedge-mapper 0.12.0
│   │       ├── tedge-log-plugin 0.12.0
│   │       ├── c8y_mapper_ext 0.12.0
│   │       ├── c8y_http_proxy 0.12.0
│   │       ├── c8y-log-plugin 0.12.0
│   │       ├── c8y-device-management 0.12.0
│   │       └── c8y-configuration-plugin 0.12.0
│   └── async-tungstenite 0.18.0
└── rustls 0.20.8
    ├── tungstenite 0.17.3
    ├── tokio-rustls 0.23.4
    ├── hyper-rustls 0.23.2
    └── certificate 0.12.0
        ├── tedge_config 0.12.0
        ├── tedge 0.12.0
        └── mqtt_channel 0.12.0
```

Below are steps taken to upgrade all of webpki's dependents, and encountered problems.

**Note**: Instead of searching for a minimal version which has the fix, I tried upgrading to the latest versions, and verifying that they have the fix. So by _Version with fix_ below I don't mean a version in which a fix appeared, but a target upgrade version where the fix is verified to exist.

### `rustls 0.20.8`

Version with fix: `0.21.6`

When attempting to update `rustls` to `0.21.6` in `crates/common/certificate`, there is an error in an error translating function in `crates/common/certificate/src/lib.rs:153`. It uses an error downcast, which makes it tricky. Though the call site of the function is more than 2 years old at this point, so perhaps it can be rewritten more easily.

It's also depended on by `tokio-rustls 0.23.4`.

Status: needs more work

### `tungstenite 0.17.3`

our crate: `c8y_remote_access_plugin`

Version with fix: `0.20`

`tungstenite` no longer uses `webpki` in currently-latest version `0.20.0`.

To update `tungstenite`, it's dependents `async-tungstenite` and `ws_stream_tungstenite` had to be updated as well. `ws_stream_tungstenite` is the smallest, and it seems wasn't yet updated to the latest versions of `tungstenite` and `async-tungstenite`, preventing us from updating to the latest versions of them.

- `tungstenite` was updated from `0.17.3` to `0.19.0` (latest `0.20.0`)
- `async-tungstenite` was updated from `0.18.0` to `0.22.2` (latest `0.23.0`)
- `ws_stream_tungstenite` was updated from `0.9.0` to latest `0.10.0`

Because `tungstenite 0.19.0` still uses webpki, this update did not resolve the issue.

But after removing `tokio-rustls-native-certs` feature from `async-tungstenite`, it caused `webpki` to not be depended on by `tungstenite`, because of `__rustls-tls` feature.

The issue was fixed, but there could be a POSSIBLE REGRESSION in `c8y_remote_access_plugin` resulting from the fact that we no longer use feature `tokio-rustls-native-certs`.

Status: needs verification

### `tokio-rustls 0.23.4`

Version with fix: `0.24.1`

Dependents of this crate include `rumqttc` and `rumqttd`, latest versions of which update the dependency to `0.24`, which contains a fix. But it could be problematic to rewrite all the rumqttc and rumqttd code we have because a major API change taken place between the version we currently use and the latest version.

To update `rumqttc`, we'd have to also update `rustls` version in `certificate`, hitting the error downcast issue.

It's the most dependents on the tree, so there can be more issues with this one.

Status: needs more work

**Comment by didier-wenzek** [comment]
Thank you for this thorough analysis of the issue.

> The issue was fixed, but there could be a POSSIBLE REGRESSION in `c8y_remote_access_plugin` resulting from the fact that we no longer use feature `tokio-rustls-native-certs`.

Indeed, this will be a source of confusion as a certificate can be trusted by some components of the system and not others. See https://github.com/thin-edge/thin-edge.io/issues/1678
