### ISSUE TITLE
Fix `download` crate unit tests that fail or do not terminate due to lack of disk space on Github CI runner

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2208]
**TODO**

- [x] try to reproduce the issue locally
- [x] fix tests not terminating because of no disk space
- [x] find out how to reduce amount of disk space used on Github CI runner

**Describe the bug**

Some of the unit tests of the download crate fail or do not terminate, as can be seen in this CI run:

https://github.com/thin-edge/thin-edge.io/actions/runs/6026288086/job/16348875869

For now, failing tests were ignored in https://github.com/thin-edge/thin-edge.io/commit/3cf64981878ee3c65063b07631023ce3eda5f47e, and will be re-enabled once the issue has been fixed.

There are 2 problems to be solved:

- [x] ~Resolve lack of disk space on the CI runner, which is a problem in itself and could potentially cause other tests to fail as well~ fixed in #2217
- [x] ~Figure out why some tests do not terminate and make them terminate with a failure~ fixed in #2210 

**To Reproduce**

To reproduce the issue, one needs to re-enable ignored tests and run `pull-request-checks` CI workflow in this very repository. I tried running this workflow on my fork, but for some reason the amount of space used was lower, so writes did not fail (65GB used here vs 72GB used by the main repository workflow):

https://github.com/Bravo555/thin-edge.io/actions/runs/6035002974/job/16374496858

This can also be a clue how to reclaim disk space used in the main repository.

The issue can also be easily reproduced locally by filling up your disk:

1. remove `#[ignore ...]` directives from affected tests
1. run `cargo llvm-cov -p download` to generate artifacts
2. run `dh -h` to see how much free space there is in the filesystem
3. run `fallocate -l SIZE big_file` where `SIZE` is available space on your filesystem
4. run `cargo llvm-cov -p download` again
5. some of the tests should fail and some should not terminate

**Expected behavior**

The target state after resolution of this issue is the following:

1. fix the tests that do not terminate
6. reclaim enough disk space so that we're not running into any write errors
7. have some sort of way to monitor resource usage by the runners so that we can more quickly find issues caused by lack of resources on the CI runner
8. determine if Github hosted runners are enough for us, and whether or not should we set up self-hosted runners.

**Comment by didier-wenzek** [comment]
I would be also sure that downloads don't block for ever when there is not enough space left. In other words, I want to be sure that only the tests are buggy.

The tests can use [`tmpfs`](https://www.man7.org/linux/man-pages/man5/tmpfs.5.html)  to not depend on the  disk space actually available or to simulate a full disk.

**Comment by Bravo555** [comment]
> I would be also sure that downloads don't block for ever when there is not enough space left. In other words, I want to be sure that only the tests are buggy.

From what I can see, it seems to only affect the tests. After I've reproduced the issue locally, it seems like the line:

https://github.com/thin-edge/thin-edge.io/blob/c07cf4791e394da90c9af2d2d12aaf6e58264a49/crates/common/download/src/download.rs#L677

doesn't terminate the test as it should, whereas `panic!`ing woks fine. So I think the solution would be to remove anyhow from async unit tests as they usually do not need it, but I'm still trying to figure out why `bail!` doesn't work when `Downloader::download` is called.

**Comment by Bravo555** [comment]
Fixed in #2210 and #2217.
