### ISSUE TITLE
Update c8y-mapper to handle config commands

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2292]
Subtask for #2098 

Todo:
- [x] Update `tedge_downloader_ext` to accept any type of key for the request/result. #2291
- [x] `tedge-agent` creates `/var/tedge/cache` directory. #2293 
- [x] `tedge-mapper-c8y` handles `config_update` and `config_snapshot` commands.#2303

**Comment by rina23q** [comment]
Verification must be done for #2098 together with all other components, i.e. tedge-mapper-c8y, tedge-configuration-plugin, doc, and robot tests. Therefore I close this sub-task.
